windowrule = match:class (vlc), opaque on
windowrule = match:class (jetbrains-studio|jetbrains-idea-ce|jetbrains-rustrover), opaque on
windowrule = match:class ^(firefox)$, rounding 3
windowrule = match:class ^(vesktop)$, workspace 3 silent
windowrule = match:class ^(io.github.kukuruzka165.materialgram|zapzap)$, workspace 4 silent
windowrule = match:class ^(com.github.neithern.g4music|org.qbittorrent.qBittorrent)$, float on
windowrule = match:class ^(ball-game|desert-rain), float on, fullscreen on
windowrule = match:class ^(it.mijorus.smile)$, float on
windowrule = match:class ^(steam)$, float on, opacity 0.80,
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:title ^(.*Network Manager.*)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on, size 855 525, center on
windowrule = match:class ^(pinentry-), stay_focused on
windowrule = match:class ^(thunar)$, match:title rename, float on

windowrule = match:class ^(thunar)$, opacity 0.85
windowrule = match:class ^(discord|Vesktop|vesktop)$, opacity 0.85
windowrule = match:class ^(v2rayN)$, opacity 0.9
windowrule = match:class ^(ONLYOFFICE)$, opacity 0.90
windowrule = match:class ^(org.telegram.desktop)$, opacity 0.80
windowrule = match:class ^(soffice|libreoffice-writer|org.libreoffice.LibreOffice)$, opacity 0.90
windowrule = match:class ^(Motrix)$, opacity 0.80

#Picture-in-Picture special treatment
windowrule = match:title ^(Picture-in-Picture), float on
windowrule = match:title ^(Picture-in-Picture), center true
windowrule = match:title ^(Picture-in-Picture), size 585 330
windowrule = match:title ^(Picture-in-Picture), move 100%-816 50
windowrule = match:title ^(Picture-in-Picture), pin on
windowrule = match:title ^(Picture-in-Picture), opacity 1 0.8
windowrule = match:title ^(Picture-in-Picture), no_initial_focus on
windowrule = match:title ^(Picture-in-Picture), opacity 1

#layerrules
layerrule = match:namespace ^(waybar)$, blur on
layerrule = match:namespace ^(logout_dialog)$, blur on
layerrule = match:namespace ^(wofi)$, blur on
layerrule = match:namespace ^(wofi)$, ignore_alpha 0.14
layerrule = match:namespace ^(swaync-control-center)$, blur on
layerrule = match:namespace ^(swaync-notification-window)$, blur on
layerrule = match:namespace ^(swaync-control-center)$, ignore_alpha 0.1
layerrule = match:namespace ^(swaync-notification-window)$, ignore_alpha 0.1
