workspace=special:overview,gapsout:80
workspace=special:running,rounding:false,gapsout:80

workspace=1,gapsout:20,gapsin:10,bordersize:3
workspace=2,bordersize:4,gapsout:20
workspace=3,gapsout:30,bordersize:3
workspace=4,gapsout:50
workspace=5,gapsout:30,gapsin:10,bordersize:3
workspace=6,gapsout:30,gapsin:10,bordersize:3
workspace=7,gapsout:30,gapsin:10,bordersize:3
workspace=8,gapsout:30,gapsin:10,bordersize:3
